version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://postgres:admin@postgres/pizza_shops
      - ELASTICSEARCH_URL=https://localhost:9200
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pizza_shops
    volumes:
      - postgres_data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:latest
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
volumes:
  postgres_data:
  elasticsearch_data: